# Generated by Django 4.0.3 on 2022-04-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roommodel_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
